name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint with ESLint
      run: npm run lint
      continue-on-error: true

    - name: Type check with TypeScript
      run: npm run typecheck
      continue-on-error: true

    - name: Build TypeScript
      run: npm run build

    - name: Test build output
      run: |
        # Verify build artifacts exist
        ls -la dist/
        # Check if main files are present
        test -f dist/index.js
        test -f dist/bot.js

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: Check for known vulnerabilities
      run: |
        # Install audit-ci for more detailed security checking
        npm install -g audit-ci
        audit-ci --moderate
      continue-on-error: true
